Repository GSG-G7/mental-snapp, pull requests merged in 2019-11, with the labels that each got.

#70 13 server error
  src/containers/assets/serverError.svg
  src/containers/errors/ServerError/index.js
  src/containers/errors/ServerError/servererror.stories.js
  src/containers/errors/ServerError/style.css
Labels: For Merge

#75 Journal Card
  package.json
  src/components/JournalCard/index.jsx
  src/components/JournalCard/journalCard.stories.js
  src/components/JournalCard/style.css
Labels: For Merge

#83 Logo Header
  public/_redirects
  src/components/LogoHeader/LogoHeader.stories.js
  src/components/LogoHeader/index.jsx
  src/components/LogoHeader/style.css
  src/components/assets/images/logo.png
  src/constants/routes.js
Labels: Awaiting Review

#77 Sign up page
  .eslintrc.js
  src/components/FacebookButton/index.js
  src/components/FacebookButton/style.css
  src/components/GoogleButton/index.js
  src/components/GoogleButton/style.css
  src/components/Header/header.css
  src/components/Header/index.js
  src/components/MainHeading/index.jsx
  src/components/MainHeading/main-heading.css
  src/components/MainHeading/main-heading.test.js
  src/components/MainHeading/style.css
  src/containers/SignUp/index.js
  src/containers/SignUp/signUp.css
  src/containers/SignUp/signUp.jsx
  src/containers/assets/images/facebook.svg
  src/containers/assets/images/google.svg
  src/routes/App/style.css
Labels: For Merge

#71 Forgot Password
  .eslintrc.js
  src/components/Header/header.css
  src/containers/ForgotPassword/forgotPass.css
  src/containers/ForgotPassword/forgotPass.jsx
  src/containers/ForgotPassword/forgotPass.test.js
  src/containers/ForgotPassword/index.js
  src/containers/assets/images/forgotPass.svg
  src/routes/App/style.css
Labels: For Merge

#80 24 question
  src/containers/About/about.css
  src/containers/About/about.jsx
  src/containers/Landing/index.js
  src/containers/Landing/landing.css
  src/containers/Questions/data.js
  src/containers/Questions/index.js
  src/containers/Questions/questionValidation.js
  src/containers/Questions/questions.css
  src/containers/Questions/questions.jsx
  src/routes/App/style.css
Labels: For Merge

#81 21 feed page
  .eslintrc.js
  src/components/LogoHeader/index.jsx
  src/components/LogoHeader/style.css
  src/components/assets/images/logo.svg
  src/containers/Feed/data.js
  src/containers/Feed/feeds.css
  src/containers/Feed/feeds.jsx
  src/containers/Feed/index.js
Labels: Awaiting Review

#84 Account settings
  .eslintrc.js
  src/containers/AccountSettings/accountSettings.css
  src/containers/AccountSettings/accountSettings.jsx
  src/containers/AccountSettings/accountSettings.test.js
  src/containers/AccountSettings/index.js
Labels: For Merge

#85 27 home page
  src/components/JournalCard/index.jsx
  src/components/JournalCard/journalCard.stories.js
  src/components/JournalCard/style.css
  src/components/LogoHeader/style.css
  src/constants/routes.js
  src/containers/Home/home.css
  src/containers/Home/home.jsx
  src/containers/Home/index.js
  src/containers/assets/icons/editIcon.svg
  src/routes/App/style.css
Labels: For Merge

#87 Edit profile page
  src/containers/EditAccount/editAccount.css
  src/containers/EditAccount/editAccount.jsx
  src/containers/EditAccount/editAccount.test.js
  src/containers/EditAccount/index.js
Labels: For Merge

#86 Confirm password page
  src/containers/ConfirmPassword/confirmPass.css
  src/containers/ConfirmPassword/confirmPass.jsx
  src/containers/ConfirmPassword/confirmPass.test.js
  src/containers/ConfirmPassword/index.js
  src/containers/assets/images/confirmPass.svg
Labels: For Merge

#89 10 Journal
  src/components/Journal/index.js
  src/components/Journal/style.css
  src/containers/Journal/fakeData.js
  src/containers/Journal/index.js
  src/containers/Journal/journal.css
  src/containers/Journal/journal.jsx
Labels: For Merge

#79 Heat Map
  package-lock.json
  package.json
  src/components/LogoHeader/index.jsx
  src/components/assets/images/logo1.png
  src/containers/HeatMap/data.js
  src/containers/HeatMap/heatMap.css
  src/containers/HeatMap/heatMap.jsx
  src/containers/HeatMap/index.js
  src/containers/Landing/landing.css
  src/containers/Questions/questions.css
  src/containers/assets/images/logo.png
  src/containers/assets/images/noJournals.svg
  src/utils/dates.js
  src/utils/toolTipData.js
Labels: For Merge

#90 Handle delete
  .eslintrc.js
  src/components/JournalCard/index.jsx
  src/containers/Feed/data.js
  src/containers/Feed/feeds.jsx
  src/containers/Home/home.jsx
  src/containers/Home/index.js
  src/containers/Home/staticData.js
  src/containers/Journal/index.js
  src/containers/SignUp/signUp.jsx
  src/routes/App/style.css
Labels: For Merge

#94 93 auth firestore
  .gitignore
  src/containers/Firebase/context.js
  src/containers/Firebase/firebase.js
  src/containers/Firebase/index.js
Labels: Awaiting Review

#102 Signup route
  src/containers/Firebase/firebase.js
  src/containers/SignUp/signUp.css
  src/containers/SignUp/signUp.jsx
Labels: Awaiting Review

#103 38 sign in
  src/containers/Firebase/firebase.js
  src/containers/SignIn/index.js
Labels: Awaiting Review

#95 40 question firestore
  src/containers/Home/index.js
  src/containers/Questions/index.js
Labels: Awaiting Review

#96 46 delete firebase
  src/containers/Feed/feeds.jsx
Labels: Awaiting Review

#99 HeatMap
  src/components/JournalCard/index.jsx
  src/containers/Firebase/firebase.js
  src/containers/HeatMap/data.js
  src/containers/HeatMap/filter.js
  src/containers/HeatMap/heatMap.jsx
  src/containers/HeatMap/index.js
Labels: In progress

#105 44 edit goal | get recent entries
  src/containers/Home/home.css
  src/containers/Home/home.jsx
  src/containers/Home/index.js
Labels: Awaiting Review

#109 42 get user informatiom
  src/containers/AccountSettings/accountSettings.jsx
  src/containers/AccountSettings/index.js
  src/containers/SignIn/index.js
  src/containers/SignIn/signIn.css
  src/containers/SignUp/signUp.css
  src/containers/SignUp/signUp.jsx
  src/routes/App/style.css
Labels: Awaiting Review

#111 Confirm password
  src/components/JournalCard/style.css
  src/components/MainHeading/style.css
  src/components/subHeading/subHeading.css
  src/containers/AccountSettings/accountSettings.jsx
  src/containers/AccountSettings/index.js
  src/containers/ConfirmPassword/confirmPass.css
  src/containers/ConfirmPassword/confirmPass.jsx
  src/containers/ForgotPassword/forgotPass.css
  src/containers/SignIn/signIn.css
  src/routes/App/style.css
Labels: Awaiting Review

#100 Edit Account
  src/components/JournalCard/style.css
  src/containers/EditAccount/editAccount.css
  src/containers/EditAccount/editAccount.jsx
  src/containers/EditAccount/index.js
  src/containers/Feed/feeds.css
  src/containers/Feed/feeds.jsx
  src/containers/SignIn/index.js
Labels: Awaiting Review

#108 107 Log out | firebase function
  src/containers/AccountSettings/index.js
  src/containers/Firebase/firebase.js
Labels: Awaiting Review

#114 Update feed page
  src/containers/Feed/feeds.jsx
Labels: Awaiting Review

#110 Forgot password
  src/containers/Firebase/firebase.js
  src/containers/ForgotPassword/forgotPass.jsx
Labels: Awaiting Review

#113 112 Journal page | Firebase
  src/containers/Home/home.jsx
  src/containers/Home/index.js
  src/containers/Journal/index.js
  src/containers/Journal/journal.css
Labels: Awaiting Review, Firebase

#117 Question page | fix delete function
  src/components/JournalCard/index.jsx
  src/containers/Feed/feeds.jsx
  src/containers/Home/index.js
  src/containers/Questions/data.js
  src/containers/Questions/index.js
  src/containers/SignUp/signUp.jsx
Labels: Awaiting Review

#104 Authentication & Authorization
  package-lock.json
  package.json
  src/containers/Session/context.js
  src/containers/Session/index.js
  src/containers/Session/withAuthentication.js
  src/containers/Session/withAuthorization.js
Labels: Authentication, Awaiting Review

#120 Set user goal to be as the title of the last question(developing)
  src/containers/Questions/index.js
  src/containers/SignUp/signUp.jsx
Labels: Awaiting Review

#118 Session handling to check if the user is authenticated.
  src/containers/About/about.jsx
  src/containers/AccountSettings/index.js
  src/containers/ConfirmPassword/confirmPass.jsx
  src/containers/EditAccount/index.js
  src/containers/Feed/feeds.jsx
  src/containers/ForgotPassword/forgotPass.jsx
  src/containers/HeatMap/index.js
  src/containers/Home/index.js
  src/containers/Journal/index.js
  src/containers/Landing/index.js
  src/containers/Questions/index.js
  src/containers/Session/context.js
  src/containers/Session/index.js
  src/containers/Session/withAuthentication.js
  src/containers/Session/withAuthorization.js
  src/containers/SignIn/index.js
  src/containers/SignUp/signUp.jsx
  src/containers/errors/AuthenticationError/index.js
  src/routes/App/index.js
Labels: Awaiting Review

#106 Google & Facebook Sign In
  src/components/FacebookButton/index.js
  src/components/GoogleButton/index.js
  src/containers/Firebase/firebase.js
  src/containers/SignIn/signIn.css
Labels: Awaiting Review

#119 HeatMap
  src/containers/HeatMap/filter.js
  src/containers/HeatMap/heatMap.css
  src/containers/HeatMap/heatMap.jsx
  src/containers/HeatMap/index.js
  src/containers/Home/home.jsx
  src/containers/SignIn/index.js
Labels: Awaiting Review

#127 Animate cards
  package-lock.json
  package.json
  public/index.html
  src/components/JournalCard/index.jsx
  src/containers/HeatMap/heatMap.jsx
  src/containers/Home/home.jsx
Labels: Awaiting Review

#126 Fix style
  src/components/BackButton/backbutton.css
  src/components/Header/header.css
  src/components/Journal/index.js
  src/components/Journal/style.css
  src/components/JournalCard/index.jsx
  src/components/JournalCard/style.css
  src/components/LogoHeader/index.jsx
  src/components/LogoHeader/style.css
  src/components/MainHeading/style.css
  src/components/navigationBar/navigation.css
  src/containers/AccountSettings/accountSettings.css
  src/containers/AccountSettings/accountSettings.jsx
  src/containers/ConfirmPassword/confirmPass.css
  src/containers/ConfirmPassword/confirmPass.jsx
  src/containers/EditAccount/editAccount.css
  src/containers/EditAccount/editAccount.jsx
  src/containers/Feed/feeds.css
  src/containers/Feed/feeds.jsx
  src/containers/ForgotPassword/forgotPass.css
  src/containers/HeatMap/heatMap.css
  src/containers/HeatMap/heatMap.jsx
  src/containers/Home/home.css
  src/containers/Home/home.jsx
  src/containers/Home/index.js
  src/containers/Journal/journal.css
  src/containers/Journal/journal.jsx
  src/containers/Landing/index.js
  src/containers/Landing/landing.css
  src/containers/SignIn/index.js
  src/containers/SignIn/signIn.css
  src/containers/SignUp/signUp.jsx
  src/routes/App/style.css
Labels: Awaiting Review

#130 fix the popup style
  src/containers/Journal/journal.css
  src/containers/Questions/questions.css
Labels: Awaiting Review

#133 Bug Fixed
  src/containers/HeatMap/index.js
Labels: Awaiting Review

#131 Initial handover fixes
  src/containers/Feed/feeds.jsx
  src/containers/HeatMap/heatMap.jsx
  src/containers/Home/home.css
  src/containers/Home/home.jsx
  src/containers/Session/withAuthentication.js
  src/containers/SignUp/signUp.jsx
Labels: Awaiting Review

#128 123 previous question
  README.md
  src/containers/About/about.test.js
  src/containers/EditAccount/editAccount.jsx
  src/containers/Feed/feeds.test.js
  src/containers/HeatMap/heatMap.test.js
  src/containers/Home/home.jsx
  src/containers/Home/home.test.js
  src/containers/Journal/journal.test.js
  src/containers/Questions/index.js
  src/containers/Questions/questions.test.js
  src/containers/SignIn/signIn.stories.js
  src/containers/SignIn/signIn.test.js
  src/containers/SignUp/signUp.test.js
  src/containers/assets/images/figma-design.png
  src/containers/assets/images/serverError.svg
  src/containers/assets/images/vector.svg
  src/containers/errors/ClientError/index.js
  src/containers/errors/ClientError/style.css
  src/containers/errors/ServerError/index.js
Labels: Awaiting Review

#140 Settings google account
  src/components/GoogleButton/index.js
  src/containers/AccountSettings/accountSettings.jsx
  src/containers/EditAccount/editAccount.jsx
Labels: For Merge

#137 132 readme
  README.md
Labels: Awaiting Review

#141 132 readme
  README.md
Labels: Awaiting Review
