Repository GSG-G7/mental-snapp, pull requests merged in 2019-10, with the labels that each got.

#8 Readme
  README.md
Labels: Awaiting Review, documentation

#30 create file structure
  mental-snapp/client/.gitignore
  mental-snapp/client/package-lock.json
  mental-snapp/client/package.json
  mental-snapp/client/public/index.html
  mental-snapp/client/public/manifest.json
  mental-snapp/client/public/robots.txt
  mental-snapp/client/src/containers/About/index.js
  mental-snapp/client/src/containers/About/style.css
  mental-snapp/client/src/containers/AccountSettings/index.js
  mental-snapp/client/src/containers/AccountSettings/style.css
  mental-snapp/client/src/containers/ConfirmPassword/index.js
  mental-snapp/client/src/containers/ConfirmPassword/style.css
  mental-snapp/client/src/containers/EditAccount/index.js
  mental-snapp/client/src/containers/EditAccount/style.css
  mental-snapp/client/src/containers/Feed/index.js
  mental-snapp/client/src/containers/Feed/style.css
  mental-snapp/client/src/containers/ForgetPassword/index.js
  mental-snapp/client/src/containers/ForgetPassword/style.css
  mental-snapp/client/src/containers/HeatMap/index.js
  mental-snapp/client/src/containers/HeatMap/style.css
  mental-snapp/client/src/containers/Home/index.js
  mental-snapp/client/src/containers/Home/style.css
  mental-snapp/client/src/containers/Journal/index.js
  mental-snapp/client/src/containers/Journal/style.css
  mental-snapp/client/src/containers/Landing/index.js
  mental-snapp/client/src/containers/Landing/style.css
  mental-snapp/client/src/containers/Questions/index.js
  mental-snapp/client/src/containers/Questions/style.css
  mental-snapp/client/src/containers/SignIn/index.js
  mental-snapp/client/src/containers/SignIn/style.css
  mental-snapp/client/src/containers/SignUp/index.js
  mental-snapp/client/src/containers/SignUp/style.css
  mental-snapp/client/src/containers/errors/AuthenticationError/index.js
  mental-snapp/client/src/containers/errors/AuthenticationError/style.css
  mental-snapp/client/src/containers/errors/ClientError/index.js
  mental-snapp/client/src/containers/errors/ClientError/style.css
  mental-snapp/client/src/containers/errors/ServerError/index.js
  mental-snapp/client/src/containers/errors/ServerError/style.css
  mental-snapp/client/src/index.js
  mental-snapp/client/src/routes/App/App.css
  mental-snapp/client/src/routes/App/App.js
Labels: Awaiting Review

#33 Eslint
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/containers/About/index.js
  client/src/containers/About/style.css
  client/src/containers/AccountSettings/index.js
  client/src/containers/AccountSettings/style.css
  client/src/containers/ConfirmPassword/index.js
  client/src/containers/ConfirmPassword/style.css
  client/src/containers/EditAccount/index.js
  client/src/containers/EditAccount/style.css
  client/src/containers/Feed/index.js
  client/src/containers/Feed/style.css
  client/src/containers/ForgetPassword/index.js
  client/src/containers/ForgetPassword/style.css
  client/src/containers/HeatMap/index.js
  client/src/containers/HeatMap/style.css
  client/src/containers/Home/index.js
  client/src/containers/Home/style.css
  client/src/containers/Journal/index.js
  client/src/containers/Journal/style.css
  client/src/containers/Landing/index.js
  client/src/containers/Landing/style.css
  client/src/containers/Questions/index.js
  client/src/containers/Questions/style.css
  client/src/containers/SignIn/index.js
  client/src/containers/SignIn/style.css
  client/src/containers/SignUp/index.js
  client/src/containers/SignUp/style.css
  client/src/containers/errors/AuthenticationError/index.js
  client/src/containers/errors/AuthenticationError/style.css
  client/src/containers/errors/ClientError/index.js
  client/src/containers/errors/ClientError/style.css
  client/src/containers/errors/ServerError/index.js
  client/src/containers/errors/ServerError/style.css
  client/src/index.js
  client/src/routes/App/index.js
  client/src/routes/App/style.css
  mental-snapp/client/src/index.js
  mental-snapp/client/src/routes/App/App.js
Labels: Awaiting Review

#50 Client Error
  package-lock.json
  package.json
  public/index.html
  src/containers/AccountSettings/accountSettings.test.js
  src/containers/errors/ClientError/index.js
  src/containers/errors/ClientError/style.css
  src/containers/errors/ClientError/vector.svg
  src/routes/App/index.js
Labels: Awaiting Review

#59 Packages
  .eslintrc.js
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
  stories/0-Welcome.stories.js
  stories/1-Button.stories.js
Labels: Awaiting Review

#64 Main heading component
  src/components/MainHeading/index.jsx
  src/components/MainHeading/main-heading.css
  src/components/assets/fonts/VAGRounded Lt Regular.ttf
  src/components/assets/fonts/vagroun.ttf
  src/components/assets/fonts/vagroun5.ttf
  src/components/assets/fonts/vagrounded-thin.ttf
Labels: Changes Requested

#60 Create Back-Button as a common component
  src/components/BackButton/backbutton.css
  src/components/BackButton/backbutton.test.js
  src/components/BackButton/index.jsx
  src/routes/App/index.js
Labels: Awaiting Review

#72 Under construction page
  src/components/BackButton/backbutton.test.js
  src/containers/UnderConstruction/UnderConstruction.stories.js
  src/containers/UnderConstruction/index.js
  src/containers/UnderConstruction/style.css
  src/containers/assets/images/underConstruction.svg
  src/routes/App/index.js
Labels: Awaiting Review

#66 Sub Heading
  .storybook/config.js
  src/components/MainHeading/index.jsx
  src/components/MainHeading/main-heading.css
  src/components/subHeading/index.jsx
  src/components/subHeading/subHeading.css
  src/components/subHeading/subHeading.stories.js
  src/routes/App/style.css
  stories/0-Welcome.stories.js
  stories/1-Button.stories.js
Labels: Awaiting Review

#61 create authentication error page
  .eslintrc.js
  src/components/BackButton/index.jsx
  src/containers/About/index.js
  src/containers/AccountSettings/index.js
  src/containers/ConfirmPassword/index.js
  src/containers/EditAccount/index.js
  src/containers/Feed/index.js
  src/containers/ForgotPassword/index.js
  src/containers/HeatMap/index.js
  src/containers/Home/index.js
  src/containers/Journal/index.js
  src/containers/Landing/index.js
  src/containers/Questions/index.js
  src/containers/SignIn/index.js
  src/containers/SignUp/index.js
  src/containers/UnderConstruction/UnderConstruction.stories.js
  src/containers/UnderConstruction/index.js
  src/containers/assets/images/athentication.svg
  src/containers/errors/AuthenticationError/authentication.stories.js
  src/containers/errors/AuthenticationError/index.js
  src/containers/errors/AuthenticationError/style.css
  src/containers/errors/ClientError/style.css
  src/routes/App/index.js
  src/routes/App/style.css
Labels: For Merge

#76 Added the netlify badge
  README.md
Labels: Awaiting Review

#62 create about-page
  src/components/BackButton/backbutton.css
  src/containers/About/about.css
  src/containers/About/about.jsx
  src/containers/About/data.js
  src/containers/About/index.js
  src/containers/assets/images/about.svg
  src/containers/assets/images/logo.svg
Labels: For Merge

#68 57 navigation bar
  src/components/assets/icons/addNew.svg
  src/components/assets/icons/calendar.svg
  src/components/assets/icons/feedsFilter.svg
  src/components/assets/icons/homeIcon.svg
  src/components/assets/icons/settings.svg
  src/components/navigationBar/index.jsx
  src/components/navigationBar/navigation.css
  src/containers/Home/index.js
Labels: Awaiting Review

#63 create landing-page
  src/containers/Landing/index.js
  src/containers/Landing/landing.css
  src/containers/Landing/landing.stories.js
  src/containers/assets/images/landing.svg
Labels: Awaiting Review
